export const merchantData=[
    {   
        sno:1,
        uniqueId:"000057",
        name:"Roadside cafe  ",
        orderRequest:22,
        orderAccept:10,
        orderCompleted:7,
        orderCancelled:0,
        orderOutOfStock:0,
        totalCollection:1005.00,
        packagingCharges:60.00,
        taxes:0.00,
        shopRevenue:891.60,
        commision:113.40 ,
        acceptedRates:45.45,
        rejectedRate:54.55,
        riderAverageRating:5.00,
        userAverageRating:0,
        wasted:5,
        wastedPercent:22.73,
        action:"Download Report/Email Report"
    },  
    {   
        sno:2,
        uniqueId:"000057",
        name:"Roadside cafe  ",
        orderRequest:22,
        orderAccept:10,
        orderCompleted:7,
        orderCancelled:0,
        orderOutOfStock:0,
        totalCollection:1005.00,
        packagingCharges:60.00,
        taxes:0.00,
        shopRevenue:891.60,
        commision:113.40 ,
        acceptedRates:45.45,
        rejectedRate:54.55,
        riderAverageRating:5.00,
        userAverageRating:0,
        wasted:5,
        wastedPercent:22.73,
        action:"Download Report/Email Report"
    },  
    {   
        sno:3,
        uniqueId:"000057",
        name:"Roadside cafe  ",
        orderRequest:22,
        orderAccept:10,
        orderCompleted:7,
        orderCancelled:0,
        orderOutOfStock:0,
        totalCollection:1005.00,
        packagingCharges:60.00,
        taxes:0.00,
        shopRevenue:891.60,
        commision:113.40 ,
        acceptedRates:45.45,
        rejectedRate:54.55,
        riderAverageRating:5.00,
        userAverageRating:0,
        wasted:5,
        wastedPercent:22.73,
        action:"Download Report/Email Report"
    },  
    
    


]